# Generated by Django 2.2.7 on 2020-04-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airtel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('scanned_result', models.CharField(max_length=50)),
                ('VPA', models.CharField(max_length=500)),
                ('qrcode', models.CharField(max_length=500)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Airtel',
            },
        ),
        migrations.CreateModel(
            name='company_list',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'company_list',
            },
        ),
        migrations.CreateModel(
            name='Mudra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('scanned_result', models.CharField(max_length=50)),
                ('qrid', models.CharField(max_length=500)),
                ('qrcode', models.CharField(max_length=500)),
                ('lot_number', models.CharField(max_length=20)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Mudra',
            },
        ),
        migrations.CreateModel(
            name='Paytm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('scanned_result', models.CharField(max_length=50)),
                ('qrid', models.CharField(max_length=500)),
                ('qrcode', models.CharField(max_length=500)),
                ('lot_number', models.CharField(max_length=20)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Paytm',
            },
        ),
        migrations.CreateModel(
            name='PhonePe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('scanned_result', models.CharField(max_length=50)),
                ('qrid', models.CharField(max_length=500)),
                ('qrcode', models.CharField(max_length=500)),
                ('lot_number', models.CharField(max_length=20)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'PhonePe',
            },
        ),
    ]
