# Generated by Django 2.2.9 on 2020-12-15 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('college_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('address', models.CharField(blank=True, max_length=100)),
                ('college_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('mobile', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('address', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.college')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('mobile', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('address', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.college')),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.college')),
            ],
        ),
    ]
